### ISSUE TITLE
the error of paper

### ISSUE THREAD

**Issue by July-blue** [VisionLearningGroup/OP_Match#8]
First of all, thank you very much for your excellent work. I have a question about which accuracy rate was chosen in your paper to calculate the error? Closed acc or Overall acc? I look forward to your answer. I will be very grateful！
![image](https://user-images.githubusercontent.com/53008456/171638650-851e578a-acd9-411d-8284-abadedca344d.png)

**Comment by July-blue** [comment]
![image](https://user-images.githubusercontent.com/53008456/171639013-3f707632-4afd-4d3b-b41b-46dfe7783b6b.png)

**Comment by sybapp** [comment]
I have the same problem, did you solve it please?
